apiVersion: v1
kind: Pod
metadata:
  name: pod-a
  labels:
    app: test-a
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'sleep 3600']
    imagePullPolicy: IfNotPresent
  nodeSelector:
    kubernetes.io/hostname: k8sworker1
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-b
  labels:
    app: test-b
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'sleep 3600']
    imagePullPolicy: IfNotPresent
  nodeSelector:
    kubernetes.io/hostname: k8sworker2
    ---
apiVersion: v1
kind: Pod
metadata:
  name: pod-c
  labels:
    app: test-c
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'sleep 3600']
    imagePullPolicy: IfNotPresent
  nodeSelector:
    kubernetes.io/hostname: k8sworker3

