apiVersion: v1
kind: Pod
metadata:
  name: pod-a
  labels:
    app: test-a
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'sleep 3600']
    imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-b
  labels:
    app: test-b
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'sleep 3600']
    imagePullPolicy: IfNotPresent
